### ISSUE TITLE
Support older data center format versions

### ISSUE THREAD

**Issue by alexrp** [vezel-dev/novadrop#19]
In particular:

* The 32-bit variant of the current version 6.
* The 2012-era version 3 (only 32-bit).

This would require rethinking of how the data center code is structured. In particular, since nodes and attributes have different layout, we'd need helper functions to access the raw fields correctly. Possibly other stuff.

**Comment by alexrp** [comment]
> * The 32-bit variant of the current version 6.

AFAIK there's no way to distinguish a 32-bit version 6 file from a 64-bit version 6 file. They didn't bother incrementing the version number.

**Comment by alexrp** [comment]
> The 2012-era version 3 (only 32-bit).

From Caali: This is just missing the `client_version` header field. Otherwise identical to 32-bit version 6.

**Comment by alexrp** [comment]
Some changes required for this to happen:

* Bitness must be settable on `DataCenterLoadOptions`.
* Format version (`V3`, `V6X86`, `X6X64`) must be settable on `DataCenterSaveOptions`.
* Size of nodes/attributes has to be hardcoded for each bitness instead of using `Unsafe.SizeOf<T>()`.
* Some helpers need to be written for accessing node/attribute fields (to deal with bitness-dependent padding).
* Options need to be added to novadrop-dc to specify format version and bitness (see also #38).
* Data center format documentation needs to be updated.

**Comment by AgencyDev** [comment]
Hi as requested the 92.04.dat can be found here: https://drive.google.com/file/d/1caE8SgMk4ltEn2Y-ppKTAjpUq52iQVcf/view?usp=sharing

**Comment by Archgeus** [comment]
Here's the oldest DC i have... hope it helps

https://www.mediafire.com/file/qj8ho6pzotkgky2/29.09.rar/file

Key
566E3235-0E909C17-914F164A-0E306F10

IV
1D1BF571-9F2E4D4E-C2E69778-65437E32

Thanks for your awesome job :)

**Comment by alexrp** [comment]
Just checking: Is anyone still interested in this feature today? I am considering getting around to it soon, but only if it will actually have users.

**Comment by Archgeus** [comment]
Yeah, please go for it as soon as you can.

**Comment by alexrp** [comment]
@Archgeus would you mind elaborating on your use case? Also which data center format versions you care about?

**Comment by KYGAS** [comment]
> Just checking: Is anyone still interested in this feature today? I am considering getting around to it soon, but only if it will actually have users.

I had to do some work regarding Akeron server DC recently to create a compatible PSP for it; ( not sure which version it is; `281908` if that means something )
RealEditor can parse it and I could create the data however it seems some are missing which I am not sure if they are missing because of the version difference or because of RealEditor scheme.

If novadrop would support it I could check if the issue is RE related or version difference

**Comment by Archgeus** [comment]
> @Archgeus would you mind elaborating on your use case? Also which data center format versions you care about?

I'm currently on a work of restoring 71.03 server files 

![1](https://i.ibb.co/d6xLqyM/eme.png)

But since it has been a really time-consuming i'm focusing on 92.04 until the miracle happens :)

Aside of that, i'm using 28.05 DC to collect resources in order to restore forgotten/deleted quest in early patches to my 92.04, but unfortunatelly novadrop don't work with that DC version (idk which one is to be honest, has been a tedious task using GothosDC).

Obviously in order to use more easily 92.04 DC :)

**Comment by alexrp** [comment]
Ok, I'll make this feature the priority next time I do some work on Novadrop.

**Comment by alexrp** [comment]
> Here's the oldest DC i have... hope it helps
> 
> https://www.mediafire.com/file/qj8ho6pzotkgky2/29.09.rar/file
> 
> Key 566E3235-0E909C17-914F164A-0E306F10
> 
> IV 1D1BF571-9F2E4D4E-C2E69778-65437E32
> 
> I have also more dc's oldest than 29.09 but without key/iv (26.04, 27.07)... if it helps just let me know
> 
> Thanks for your awesome job :)

This archive seems to be password-protected.

**Comment by Archgeus** [comment]
> > Here's the oldest DC i have... hope it helps
> > https://www.mediafire.com/file/qj8ho6pzotkgky2/29.09.rar/file
> > Key 566E3235-0E909C17-914F164A-0E306F10
> > IV 1D1BF571-9F2E4D4E-C2E69778-65437E32
> > I have also more dc's oldest than 29.09 but without key/iv (26.04, 27.07)... if it helps just let me know
> > Thanks for your awesome job :)
> 
> This archive seems to be password-protected.

Ooops, very important detail, my bad.

Is **RaGEZONE**

**Comment by alexrp** [comment]
OK, thanks.

`master` now has support for older format versions. Please give it a try. Usage is `--architecture <arch>` (`x86`, `x64`) when loading and `--format <format>` (`v3`, `v6x86`, `v6x64`) when saving.
