### ISSUE TITLE
Deduplication of data center nodes and attributes

### ISSUE THREAD

**Issue by alexrp** [vezel-dev/novadrop#21]
Right now, we make no effort at all to deduplicate nodes and attributes. This means that data center files we produce are roughly 2x the size of official data center files.

This would have been a bigger issue in the past when TERA was 32-bit. But with the move to 64-bit, memory is effectively a non-issue. On the other hand, if people are producing multiple translated data center files for their servers, the size increase starts to add up, making distribution of the files more of an issue.

It might be good to provide an optional mode that attempts to deduplicate nodes and attributes to bring the size down at the cost of potentially much longer packing time.

**Comment by justkeepquiet** [comment]
Hi.
I want to use novadrop to pack a 32-bit datacenter. My 92.04 datacenter packs and unpacks normally (I deleted padding and edited XSDs). However, the size of the data center is large, which causes a memory problem.

Do you plan to solve the duplicate nodes/attributes problem, or how can we do it by changing the code?

**Comment by alexrp** [comment]
This is still on the to-do list - but #19 is likely going to come first. In any case, I'm currently preoccupied with other projects, so I can't say when I'll have time to address this issue in particular.

IIRC there's nothing technically stopping this from happening. It's just a question of figuring out an algorithm that achieves a good balance of packing time and resulting size, and then implementing it. (A naive but thorough deduplication algorithm would *probably* take hours to pack.)

**Comment by alexrp** [comment]
@Roukanken42 has implemented this in #68. For anyone who's interested in this feature, please test that pull request. It would also be good if you could report the peak memory usage you see during `novadrop pack`.

**Comment by Archgeus** [comment]
![Screenshot_84](https://user-images.githubusercontent.com/85969195/218913893-537bfc84-d49a-46cd-ab9e-465c09c42924.png)

Mine jumps to 16.3 GB of ram usage, but like you said in the PR, looks like a tiny smaller than official DC

![Screenshot_85](https://user-images.githubusercontent.com/85969195/218914209-c41d0860-c049-4a5d-b5f1-dea38645b39f.png)
