### ISSUE TITLE
Freezes in game after repacking DC

### ISSUE THREAD

**Issue by justkeepquiet** [vezel-dev/novadrop#26]
Related to https://github.com/vezel-dev/novadrop/discussions/25
I also confirm this problem.

The problem appears after repacking, even if no changes have been made to the files. There are no errors during unpacking/packing.

**Comment by alexrp** [comment]
Can you please confirm whether this happens only with unpack followed by pack or also with the repack command? That would help narrow down whether it's an issue in the data center code or the XML/XSD layer.

**Comment by justkeepquiet** [comment]
The `repack` command not tested yet. I just unpack the DC and pack XMLs without changes.
I use fixed XSDs for 100.02: https://drive.google.com/file/d/1zrOtQ2zOg7wvUjxldbrwmfE39lmpne2I/view?usp=sharing

**Comment by justkeepquiet** [comment]
I checked the `repack` command now. There are no problems in the game.

**Comment by alexrp** [comment]
Thanks, I'll take a closer look.

**Comment by alexrp** [comment]
I can reproduce the issue. Given that a direct disk-to-memory-to-disk repack works fine, my hunch is that we're failing to apply attribute keys when packing from XML/XSD. This would explain why some things in the game are super slow - no keys means many common data center queries slow to a crawl.

**Comment by alexrp** [comment]
> my hunch is that we're failing to apply attribute keys

This is indeed the problem. Trying to figure out why...

**Comment by alexrp** [comment]
@justkeepquiet Give e2110a70e6aa59d54121197c6e51868e0e346b9c a try. It fixes the issue on patch 115 for me.

**Comment by justkeepquiet** [comment]
That fixed on 100.02 too. Thank you.
